# Generated by Django 5.2.1 on 2025-06-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_usuario',
            fields=[
                ('id_hu', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
