# Generated by Django 5.2.1 on 2025-06-18 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historia_usuario',
            options={'verbose_name': 'Historia de Usuario', 'verbose_name_plural': 'Historias de Usuario'},
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='estado_hu',
            field=models.CharField(choices=[('Por hacer', 'Por hacer'), ('En proceso', 'En proceso'), ('Cerrada', 'Cerrada')], default='Por hacer', max_length=20),
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='id_participacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_asignadas', to='proyectos.participacion'),
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='id_proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historias_usuario', to='proyectos.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='puntos_historia',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='tiempo_estimado',
            field=models.PositiveIntegerField(default=1, help_text='Tiempo en horas estimadas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='titulo',
            field=models.CharField(default='Titulo por definir', max_length=255),
            preserve_default=False,
        ),
    ]
