# Generated by Django 5.2.1 on 2025-06-18 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_historia_usuario_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historia_usuario',
            old_name='id_hu',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='historia_usuario',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
        migrations.RemoveField(
            model_name='historia_usuario',
            name='estado_hu',
        ),
        migrations.RemoveField(
            model_name='historia_usuario',
            name='id_participacion',
        ),
        migrations.RemoveField(
            model_name='historia_usuario',
            name='tiempo_estimado',
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='estado',
            field=models.CharField(choices=[('por_hacer', 'Por hacer'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='por_hacer', max_length=20),
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='participacion_asignada',
            field=models.ForeignKey(blank=True, help_text='Participación del desarrollador asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_asignadas', to='proyectos.participacion'),
        ),
        migrations.AddField(
            model_name='historia_usuario',
            name='tiempo_estimado_horas',
            field=models.PositiveIntegerField(default=5, help_text='Tiempo estimado en horas'),
            preserve_default=False,
        ),
    ]
