# Generated by Django 5.2.1 on 2025-06-18 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_rename_id_hu_historia_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado_tarea',
            field=models.CharField(choices=[('Por hacer', 'Por hacer'), ('En progreso', 'En progreso'), ('Hecha', 'Hecha')], default='Por hacer', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='id_hu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.historia_usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='participacion_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='proyectos.participacion'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=255),
            preserve_default=False,
        ),
    ]
