# Generated by Django 5.2.1 on 2025-07-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_tarea_descripcion_tarea_estado_tarea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_proyecto',
            field=models.CharField(choices=[('activo', 'Activo'), ('en_progreso', 'En progreso'), ('hecho', 'Hecho'), ('finalizado', 'Finalizado')], default='activo', max_length=50),
        ),
    ]
