# Generated by Django 5.2.1 on 2025-06-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_actividad',
            name='historia_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia_usuario', to='proyectos.historia_usuario'),
        ),
        migrations.AddField(
            model_name='historial_actividad',
            name='participacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.participacion'),
        ),
        migrations.AddField(
            model_name='historial_actividad',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_proyecto', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='historial_actividad',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_actividades', to='proyectos.tarea'),
        ),
    ]
