# Generated by Django 5.2.1 on 2025-06-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_initial'),
        ('proyectos', '0003_historia_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_actividad',
            name='historia_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia_usuario', to='proyectos.historia_usuario'),
        ),
    ]
