# Generated by Django 5.2.1 on 2025-07-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_initial'),
        ('proyectos', '0006_alter_proyecto_estado_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_actividad',
            name='historia_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historia_hu', to='proyectos.historia_usuario'),
        ),
    ]
