# Generated by Django 5.2.1 on 2025-06-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_codigo_generado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
