# Generated by Django 5.2.1 on 2025-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rol_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripcion definida', max_length=255, null=True),
        ),
    ]
