# Generated by Django 5.2.1 on 2025-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_rol_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('project management', 'Project Management'), ('scrum_master', 'Scrum_Master'), ('developer', 'Developer')], max_length=20, unique=True),
        ),
    ]
