# Generated by Django 5.2.1 on 2025-06-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_rol_nombre_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(choices=[('project management', 'Project Management'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer')], max_length=20, unique=True),
        ),
    ]
